# Generated by Django 4.0.3 on 2022-05-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_department_dep_date_department_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dep_date',
            new_name='dept_date',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
